### ISSUE TITLE
Specification development: Form: Button

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#11]
I'm finishing work on the [button specification](https://github.com/joomla/accessibility/blob/master/docs/custom-elements/Form-Button.md).

**Comment by zwiastunsw** [comment]
Please review
- in terms of substance
- in terms of language (please: @tarotray ) 
## Issues
### Anchor in the role of a button
We have an anchor in the role of the Cancel button in the file: com_users/views/registration/tmpl/default.php
In my opinion, you should report PR
### Inconsistent name and description
In the file com_finder/views/search/tmpl/default_form.php the button is named Search (`name="Search"`), and in the description Submit (text inside the button). The name is redundant, unnecessary, and inconsistent
In my opinion, you should report PR

**Comment by zwiastunsw** [comment]
Please review
* in terms of substance (please: @armenos, @chmst, @uglyeoin, @seenee, @moje-s, @ylahav)      
* in terms of language (please: @tarotray )

**Comment by chmst** [comment]
Maybe the attribute "aria-pressed = true/false" for toggle-buttons should be described too?https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

Issues:
The name indeed seems to be superfluous.  But as it is used in so many forms for filter input, there should be a reason for it. Let us try to find out.

**Comment by mbabker** [comment]
In the case of buttons, the name isn't required.  The name attribute is really only necessary to identify the fields when they're submitted to the server (and I guess you could also build CSS selectors with them).

**Comment by zwiastunsw** [comment]
The attribute "aria-pressed = true/false" for the button is needed when a button is a different HTML element  such as a `div` or `a`
