### ISSUE TITLE
How to get new members and volunteers to the JAT?

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#14]
Any ideas? Suggestions for action?

**Comment by chmst** [comment]
Translation: Any Ideas, what can we do?

**Comment by zwiastunsw** [comment]
:) 
Any ideas? Suggestions for action?

**Comment by seenee** [comment]
we're having a session about accessibility at JWC
it's a great occassion to invite ppl to the team
don't you think?

and the other way is to communicate with marketing team to prepare recruitment to the team, but for this we need to be prepared...

**Comment by chmst** [comment]
Absloutely. I will have a session at J!DD in September.

**Comment by zwiastunsw** [comment]
Three suggestions:
1. Short article about accessibility and team in JCM.
Who will write?
2. Graphic banner for social media - can you ask the marketing team? Any content ideas?
3. The announcement in the Joomla group on Facebook. Who will prepare?

**Comment by ylahav** [comment]
@armenos - what is the action that you assigned me - what I have to do?

**Comment by armenos** [comment]
@ylahav just sharing your idea about this topic

**Comment by armenos** [comment]
Those presented ideas are fine
- Mentioning about JAT in every presentation and inviting people to join and help.
- Writing article about our team in JCM is good idea, we can ask Simon Grange. 
I can do that, I can ask him for an interview? 

- Or we just can ask Marketing: https://github.com/joomla/joomla-marketing 
- Marketing can help us with ideas and images I think
- Writing articles about this topic is also good, we can do this in little pieces. 
Like topic about pictures, then about keyboard navigation, etc. 

https://community.joomla.org/blogs.html
https://magazine.joomla.org/

- On volunteers portal we can bring every week a short report about our progress
https://volunteers.joomla.org/teams/accessibility-team
Maybe we should first discuss what each of us likes to do, but I suggest to discuss this in another issues request.

**Comment by armenos** [comment]
Creating welcome video and tutorial how volunteers can join us :)

**Comment by uglyeoin** [comment]
I can help with banners/graphics.  They won't take me too long so those are jobs I can do quite quickly.  I can contact marketing and get their templates if you want me to do any of this stuff.

I'm on the recruitment team but it is very quiet, however, I do have a few people I have recruited so far I could offer them a chance to do things on this group if you have specific tasks that I can offer them.

I can also start recruiting specifically for this group BUT I do NOT want to do so if the people just get left without a job to do as I know how hard it is to keep volunteers when they have a bad experience.  If you want me to recruit people to this team then I would ask that when a new member joins we assign them a mentor (or two) that will help them to integrate into the team.  I suggest if they are a coder they have a coder as a mentor and so on and so forth.  @armenos do you think this is agreeable?

**Comment by uglyeoin** [comment]
If you need me to do anything at my user group (Joomla! User Group London) - www.joomlalondon.co.uk I can do.  I have full access to the website and I can do a talk at my monthly meeting if you want.  I also attend Joomla! Day UK each year so I am happy to represent us there if need be.  I'm pretty social I like talking to people so more than happy to do things like that.

**Comment by uglyeoin** [comment]
I met the guy who is trying to start the podcast on Joomla! I think I can get us a slot on there to be interviewed.  I think @armenos is the best person to be interviewed as he is our leader and can portray our vision well.

**Comment by zwiastunsw** [comment]
@uglyeoin wrote:
> I can also start recruiting specifically for this group BUT I do NOT want to do so if the people just get left without a job to do as I know how hard it is to keep volunteers when they have a bad experience. 

In my opinion, we can not wait until we can allocate mentors to novices. Because we do not have candidates for mentors. We lack people with experience in accessibility testing, accessibility audits. We must first attract such people.
The work is waiting, for example, to plan and execute site audits in joomla.org, test new Joomla UI components (custom-elements)
Therefore, I would add one more to the already submitted ideas:
8. More accurate description (like job offers): Who we need? What competencies should the people we need? What kind of work do we need volunteers?

**Comment by zwiastunsw** [comment]
Let's summarize. We have some suggestions for promotional JAT:
1. Presentations during Joomla! events (JWC, JoomlaDays, JUGs).
2. Article about JAT on joomla.org (Joomla! Community Magazin).
3. Graphics inviting to JAT.
4. Text inviting to JAT.
5. Recruitment in social media (graphics + text).
6. Team reports.
7. Articles about accessibility in the Joomla! Community Magazin.
8. More accurate description (like job offers): Who we need? What competencies should the people we need? What kind of work do we need volunteers?

Tasks 2 through 8 require contractors. Who will take?

**Comment by armenos** [comment]
I think I have to do Number 2 and 7 maybe we can do this together?

**Comment by seenee** [comment]
6 is mine ;)
I can also contact marketing to get 3. and they might help with 4. but could you tell me what do we need this text for @zwiastunsw ? social media?
it's still to early for 5. I guess, not before we finish 8.

**Comment by zwiastunsw** [comment]
When I want to join the Marketing team, I have an invitation on the volunteer's website and a link to the survey. Could anyone prepare such a solution for the JAT?
