### ISSUE TITLE
Mini Joomla accessibility test

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#18]
**My proposition**:
# Project: Mini Joomla accessibility test.
## Two goals:
1. Test and evaluate the **basic features of Joomla** - common features such as search, login, and **typical pages** such as blog, category list, and more.
2. Involve more volunteers to test the accessibility of Joomla.
## How?
Every week we announce a task: What to test? We give instructions on how to test. We give the report template. We wait 7 days for the test reports. Then we come up with a summary. If the reports are not enough, we extend the testing deadline.
## Expected effects:
1. We will create and describe testing procedures.
2. We will provide everyone with an opportunity to actively participate in JAT work.
3. We will receive test reports in a variety of environments (browsers, operating systems, assistive technologies).
4. We will expand our team - we will get new volunteers.
5. We will get rich material to evaluate the accessibility of Joomla.

What do you think of this idea?

**Comment by chmst** [comment]
This is a good idea but ...  you mean testing a11y, not the features of joomla, right?
Woud you do this for every Version - stable and in development?

**Comment by zwiastunsw** [comment]
Of course, I mean tests a11y. 
Scope: stable and development version

**Comment by armenos** [comment]
It's a very good idea, 
This is actually one of our purpose, analyze, report and support.

Testing documentation should be part of this
If we wants to get support for testing we should provide information how to test.
