### ISSUE TITLE
Specification development: Structure - Tables

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#19]
I'm working on [a specification](https://github.com/joomla/accessibility/blob/master/docs/custom-elements/Structure-Tables.md).

Please suggestions, comments.

**Comment by zwiastunsw** [comment]
Any comments? suggestion?

**Comment by zwiastunsw** [comment]
Please review
* in terms of substance (please: @armenos, @chmst, @uglyeoin, @seenee, @moje-s, @ylahav)      
* in terms of language (please: @tarotray )

**Comment by chmst** [comment]
All right for me.
