### ISSUE TITLE
Tabs  - Request for testing

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#22]
@dgt41 asked for accessibility tests:
https://joomla-projects.github.io/custom-elements/bootstrap-demo.html
Ask for test results and comments here.

**Comment by armenos** [comment]
## Panels as tabs
**Keyboard:** I could tab to Tab panel 1 and it was possible for me to navigate with arrow keys.
**Screen reader:** pronounces the Tab panels.

## Panels as tabs with nested tabs
**Keyboard:**  I could tab and shift + tab to go forward and backward (Tab panel to Nested tab panels). 
**Screen reader:** pronounces the Tab panels. It was possible for me to navigate with arrow keys.

**Tested with:**
* Windows 10 Pro (15063.540)
* Firefox: 55.03 (32-bits)
* NVDA2: NonVisual Desktop Access 2017.3
* Color Contrast Analyser: ver.2.5.0.0

**Comment by zwiastunsw** [comment]
**Keybord support**: OK (Tab key move focus to other element, arrows keys move focus to next, previous tab)
**Screen reader**: correct annotation of the change and the status of the tabs (panels). Note: The NVDA incorrectly reports that we have one tab out of two, instead of three, but it is probably a NVDA error. ChromeVox pronounce correctly.

Tested with:
* Windows 10
* Chrome 60.0.3112.113 (64-bit)
* Firefox 55.03 (32-bit)
* NVDA 2017.3
* ChromeVox 53.0.2784.5

**Comment by chmst** [comment]
Test on FF, Win10.  both tab with and without nested tabs
Keyboard tested OK .
No screen-reader test.

HTMl inspected:
Role tablist OK
Controls OK
aria-selected OK
aria-labelledby OK

Not fond: aria-orientation  - is it important to know whether tabs are vertically or horizontally orientated?

**Comment by dgrammatiko** [comment]
So current implementation meets your requirements?
Anything more we need here? (aria-orientation)
