### ISSUE TITLE
Modal - Request for testing

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#23]
@dgt41 asked for accessibility tests:
https://joomla-projects.github.io/custom-elements/bootstrap-demo.html
Ask for test results and comments here.

**Comment by armenos** [comment]
**Keyboard**: I could open it with keyboard and I was not trapped within this window. It was possible for me to close with ‘X’ and ‘Close’ button.

**Screen reader**: screen reader did pronounce those buttons I didn’t test further, 

**Tested with:**
* Windows 10 Pro (15063.540)
* Firefox: 55.03 (32-bits)
* NVDA2: NonVisual Desktop Access 2017.3
* Color Contrast Analyser: ver.2.5.0.0

**Comment by chmst** [comment]
Test on FF newest version and edge, win10.
Keyboard OK.
Not tested Screenreder.

HTM Code inspected, Aria attributes OK.

**Comment by zwiastunsw** [comment]
**Keyboard, screen display**:
1. The tab key moves to the modal window.
2. The X button captures the cursor, allowing you to close.
3. The tab key moves to the contents of the window. 
4. The Cancel and Save changes buttons get a focus, but it is hardly visible.

**Screen reader**: It announces correctly. It's OK 

**Note**: When I testing other items, the Launch demo modal button "steal" the focus. 

**Tested with**:
* Windows 10
* Chrome 60.0.3112.113 (64-bit)
* Firefox 55.03 (32-bit)
* NVDA 2017.3
* ChromeVox 53.0.2784.5

**Comment by dgrammatiko** [comment]
First of all thanks for testing, this really helps moving forward!

> The Cancel and Save changes buttons get a focus, but it is hardly visible.

Thats the css of basic bootstrap that is totally bad, it should be fixed for the templates that Joomla will ship with

> Note: When I testing other items, the Launch demo modal button "steal" the focus.

I notice this behaviour as well, I need to review the code and figure out where it's broken. So once this is fixed I guess the A11Y team is happy with what we have so far?
Is there anything that I might have missed, that needs to be implemented?

**Comment by chmst** [comment]
The https://joomla-projects.github.io/custom-elements/bootstrap-demo.html generates the same id for different samples. I suggest to either make different test files or to make the ids unique.

**Comment by dgrammatiko** [comment]
Will fix it ASAP
