### ISSUE TITLE
Color tools – generators, simulators, checkers

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#26]
I wrote another fragment of the guide: [Color tools – generators, simulators, checkers](https://github.com/joomla/accessibility/blob/master/docs/tutorials/tools-color.md)
 
Ask for an overview and comments, suggestions.

**Comment by eddiekonczal** [comment]
I'm a relative newcomer to the team.  Are you still looking for comments and suggestions?

**Comment by chmst** [comment]
Hi, @eddiekonczal , yes please :)

**Comment by eddiekonczal** [comment]
I found very few problems with this guide - it reads well and is very useful!  Here are some comments and suggestions:

- Broken link: "Read more about visual impairments." = https://github.com/joomla/accessibility/blob/master/docs/tutorials/tutorials/understanding-disability.md
- Semi-colon and ellipsis are unclear at the end of this sentence:

> Large Text: Large-scale text and images of large-scale text have a contrast ratio of at least 3:1; […]
- Semi-colon and ellipsis are unclear at the end of this sentence; in addition, there is a ending quotation mark that is missing a beginning quotation mark:

> Large Text: Large-scale text and images of large-scale text have a contrast ratio of at least 4.5:1; […]"
- Updated link needed for Color Oracle: they have moved to http://colororacle.org/

**Comment by zwiastunsw** [comment]
thx for all comments
