### ISSUE TITLE
Road map to joomla.org accessibility

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#27]
We should deal with the accessibility of joomla.org. Step by step. We do not have enough strength and resources.

Let us consider how to fulfill our duty. Let us define a road map. I think there are a few elements that should be included.

1. Examine the current state of play of site accessibility procedures: 
- Are there any procedures? 
- Have they been written down somewhere? 
- Have you identified who is responsible for the accessibility of sites? 
- Who oversees? What is supervision?  What is the supervision mode?
- Have you set the accessibility monitoring mode?
- Have evaluation procedures been defined? 

I think that the answer to all the questions is: No. But we should examine this and write a report.

2. Perform an audit of website accessibility under the joomla.org domain.
There are 16 sites in the domain joomla. org. 
- How to conduct an audit? 
- Should all parties be audited? 
- Who will do it? 
- Will our team ever be able to perform such an audit? 
- Should an external audit not be outsourced? 

3. After evaluating the sites, outline for the Webmasters Team the changes that would be required to retrofit the site for accessibility.

4. Developing together with the Webmasters Team procedures for monitoring and maintaining accessibility joomla.org sites.

**Comment by mbabker** [comment]
You're better off going through each subdomain one by one.  There is very little in the base template that we can fix globally and each site has its own customizations.

The base template doesn't use layout overrides from core, so on many pages the markup will be the same as out-of-the-box Joomla.

Use the websites repo as a way to get a list of what sites have public code repos.  In those cases you would be able to directly propose changes through GitHub PRs.
