### ISSUE TITLE
A single page accessibility tests

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#31]
We have prepared a set of web site accessibility tests. Please review, commentary, amendments, etc.

[A single page accessibility tests](https://github.com/joomla/accessibility/blob/master/docs/testing/testing-single-page.md)

**Comment by brianteeman** [comment]
As it is a joomla document and we use en-GB by default please can you update it accordingly. For example color==> colour

For more words to watch out see the style guide https://developer.joomla.org/en-gb-user-interface-text-guidelines/words-to-watch.html
