### ISSUE TITLE
Request for accessibility auditing on the new media manager

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/accessibility#32]
### Description of the issue
The team that develops the new media manager needs your input/guidance to make the component fully accessible, thus to conform with the rest of J4

PS ping me in Glip to give people access to the demo site

**Comment by armenos** [comment]
Media Manager is an essential part of the backend, @zwiastunsw could you ask "JAT - Audit & Testing " to see how they can get involved with this.

**Comment by dgrammatiko** [comment]
Since the auditing has already started, this issue is obsolete
