### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#39]
After our discussions at JAB where I explained that you cannot copy any text from anywhere unless it is expressly stated by the source that you can copy it and that the copied text is correctly quoted and attributed.

Today I saw a pull request being merged #38 and can see that the text is a direct copy of other peoples text - specifically from the w3c

they have very specific rules and guidance when copying their documentation
https://www.w3.org/Consortium/Legal/2015/doc-license

it is great that you want to contribute to joomla but we just cant take other people's work without permission or credit.

please note that as this is a public repo we (joomla) are now in breach of copyright etc

@marcodings @wilsonge @armenos

**Comment by armenos** [comment]
I remember you said that when you link to the source, then it’s ok. Apparently, it’s never good enough.
I go to my work now; I’ll be back in the evening. But I need to prepare for my trip of tomorrow.
I’ll try to figure out this weekend and try to understand and to solve the problem.

**Comment by armenos** [comment]
https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620
https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#derivatives 
https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#mirrors
https://www.w3.org/Consortium/Legal/2002/copyright-documents-20021231.html
Stop destroying this work, please. I need to understand their legals; then I will contact them next week.

**Comment by brianteeman** [comment]
> I remember you said that when you link to the source, then it’s ok

Its not enough to just include a link - you have to clearly show what the text is that you are copying - usually by putting quotation marks.

In addition the text you are copying might have additional rules. It might say you can copy it if you do x. It might say you can never copy it unless you do y.

For work from the w3c then this is what you must do https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#docmods but it will be different for all sources

**Comment by brianteeman** [comment]
As we discussed at JAB and in Paris the /docs folder on this repo must be made private as it is all being well indexed by google. Often ranking before the original article.

**Comment by ylahav** [comment]
and from W3C FAQ:
"I have a Web site that mirrors (has copies of) useful Web documents. May I make copies of your documents and serve them from my site?
Yes."
and...
"I am a writer. May I make a "fair use" excerpt from a specification for my analysis?
Yes, if you believe your usage falls within the exception of fair use (e.g., in the U.S. § 107 Title 17. Limitations on exclusive rights: Fair use)."

**Comment by brianteeman** [comment]
1. These are NOT copies. A copy is something that is identical

2. "Fair Use" is a legal doctrine in the US. It legally means that you can selectively QUOTE from a document without asking for permission. 

So you cannot use either of these to justify the current documentation as it has been created.

They are not identical copies so you cannot use option 1
They are not quoted so you cannot use option 2

As I have already stated
> For work from the w3c then this is what you must do https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#docmods but it will be different for all sources

As it appears you are unable to follow the link I quote is here

> **May I republish W3C Documents without modifying them?**
Yes. See the next question for information about attribution.

> **_Note: W3C disapproves of and will act upon the misrepresentation of our work with respect to authorship, endorsement, or status._**

> **Do you have an example of attribution of a work under the W3C Document License?**
Unless otherwise stated, documents on the W3C site are published under the W3C Document License. The Document License contains the requirements for attribution. An example attribution would look like the following:

In additon the quoted text above is only for the documentation copied from w3c. Other text is copied from other places.

**Comment by brianteeman** [comment]
Finally as I stated at JAB. Joomla doesn't need to have a copy of anyone elses documentation. What Joomla needs is information and examples specific to a joomla website and to developers of joomla code. If you follow this link you will see a perfect example of what Joomla Accessibility documentation should be and what we desperately need.

https://make.wordpress.org/accessibility/handbook/

**Comment by zwiastunsw** [comment]
Dear @brianteeman. I share your concern about respecting copyright. That's why I wrote to W3C. That is the answer I received from Coralie Mercier. The content of my e-mail has been included in the response.

>Hello Stefan,
> On 16 May 2018, at 10:52, Stefan Wajda ... wrote:

> Hello,
> I have a problem. I am working on accessibility materials.
> Important people in my organization are concerned about not infringing on W3C intellectual rights.
> For example, I am presenting WCAG 2.0. I am pointing to principles and guidelines. I link to a W3C document.
> Here is a link to this material: https://github.com/joomla/accessibility/blob/master/docs/tutorials/sl-wcag-2-0.md
> Is everything OK? Can I do this? What else should I do to make sure there is no doubt?

> **This looks all right to me. It looks like a summary with pointers to the W3C documents.** 
> With kind regards,
> Coralie
> (Message sent from my telephone)

**Comment by brianteeman** [comment]
that page is very different to the other documents that are pure plagiarism

**Comment by zwiastunsw** [comment]
But that's exactly what you wrote about this page in your introductory comment. You claimed that this page is infringing the W3C license. 
I said at J&B that I would review all the materials again. When I started, you attacked me again. You are constantly attacking the work we are trying to do. You are discouraged, not helped.

**Comment by brianteeman** [comment]
I want Joomla to be legally safe 
I want Joomla to be providing useful documentation specifically for joomla
Simply copying other peoples documentation adds no value to Joomla
w3c lawyers (not marketing) wrote their rules. They didnt write them just for fun
You have copied other documentation not just w3c
