### ISSUE TITLE
Tables and pagination?

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#46]
If you look at any of the tables in the admin eg the table listing the articles you will see that the pagination is inside the table in the tfoot

```
<tfoot>
	<tr>
		<td colspan="<?php echo $columns; ?>"><?php echo $this->pagination->getListFooter(); ?></td>
	</tr>
</tfoot>
```

My gut feeling is that this is wrong and that the pagination should be in a `<nav>` outside of the table

Thoughts?

**Comment by brianteeman** [comment]
Actually I just went and checked J3 and there the pagination is outside of the table. So I can only assume that this is an error in J4.

Still appreciate your thoughts on this before I make the changes

**Comment by chmst** [comment]
I think you are right. The tables in list views have no footer. In J3 the table footer is empty. A empty table-footer this is not necessary in tables and therefore could be removed completely.
https://webaim.org/techniques/tables/data

**Comment by zwiastunsw** [comment]
The tfoot element does not provide any additional benefits for accessibility. 
Semantically, it is used to summarize the columns. 
> The `tfoot` element represents the block of rows that consist of the column summaries (footers) for the parent `table` element, if the `tfoot` element has a parent and it is `a table`. [HTML 5.2 Recommendation](https://www.w3.org/TR/html52/tabular-data.html#the-tfoot-element)

So you are right. 
In my opinion, it should be removed from all tables when it is empty. 
The pagination should be moved out of the table.

**Comment by brianteeman** [comment]
Thanks for confirming. I will work on this over the weekend.
