### ISSUE TITLE
Open Pull Requests

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#47]
There are several open accessibility pull requests that it would be great if you could do a quick test so that we can merge them and move forward.

https://github.com/joomla/joomla-cms/pull/21865
https://github.com/joomla/joomla-cms/pull/21724
https://github.com/joomla/joomla-cms/pull/21608
https://github.com/joomla/joomla-cms/pull/21604
https://github.com/joomla/joomla-cms/pull/21559

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/21933

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/21985

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/22008

**Comment by brianteeman** [comment]
All of these have impact and will require a lot more work to get them applied globally so prompt testing will be appreciated - I have very limited availability after the weekend for the next 4 weeks so would really like to get the work done before then

**Comment by zwiastunsw** [comment]
@brianteeman, I am very sorry. I am leaving for a week to Greece on holiday today. I cannot do anything.

**Comment by brianteeman** [comment]
Closed - obviously no one else is interested in improving the accessibility in joomla 4
