### ISSUE TITLE
alerts are not accessible for colour blind

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#49]
https://github.com/joomla-projects/custom-elements/issues/99

**Comment by zwiastunsw** [comment]
**The problem is not yet solved.**
 Brian Teeman closed it for the following reason:
> the alerts need a massive rewrite as they are being used completely wrong. It's not if this code is accessible or not but it is where it is being used in the cms. A modal alert is a style it is not necessarily a role=alert - they are not the same thing at all
