### ISSUE TITLE
Label accessibility

### ISSUE THREAD

**Issue by chmst** [joomla/accessibility#5]
Do we need a label "accessibility"? Everything here is about accessibility.

**Comment by uglyeoin** [comment]
If you click on the label does it bring up pull requests from the Joomla! Core as well as this repository?  I would suggest we leave it only for code.  It makes it easier to identify which code we need to action.

**Comment by armenos** [comment]
You see @chmst, we know you are talking about Accessibility :)
I'm closing this issue know, because it’s not an issue 😊
Contact me in private if you have suggestion on labels
