### ISSUE TITLE
title attribute

### ISSUE THREAD

**Issue by brianteeman** [joomla/accessibility#64]
I made a start today on removing the generally useless title attribute.

So far I only removed the title attribute where it is the same as the visible text.

We have a lot like this though. 
```

<th scope="row">
	<span class="icon-eye-close disabled hasTooltip" aria-hidden="true" title="No preview available. You can enable preview in the options."></span>
	<span class="sr-only">No preview available. You can enable preview in the options.</span>
	<a href="/joomla-cms/administrator/index.php?option=com_templates&amp;task=style.edit&amp;id=11" title="Edit cassiopeia - Default">
	<span class="fa fa-pencil-square mr-2" aria-hidden="true"></span>cassiopeia - Default</a>
</th>
```

This one piece of code has two examples of issues. Suggestions on how to handle these

**Comment by maliouris** [comment]
As I read here https://github.com/joomla/accessibility/issues/52 we need titles in order to have an alternative way to understand what an icon represents if we just can't or for some reason it doesn't load

**Comment by brianteeman** [comment]
But what happens for a screenreader in the second example? Do they hear it twice?

**Comment by zwiastunsw** [comment]
NVDA reads: "No preview available. You can enable preview in the options. Link cassiopeia - default"
