### ISSUE TITLE
"Search Form or Search Results" menu item: Form elements must have labels 

### ISSUE THREAD

**Issue by eddiekonczal** [joomla/accessibility#67]
## [XX x.x.x] Descriptive Title
"Search Form or Search Results" menu item: Form elements must have labels 
I am unsure what to put for XX and x.x.x

### Description of the issue

When using the Deque WorldSpace plugin for Chrome to test a "Search Form or Search Results" menu item (with "Use Search Options" turned on), the following accessibility violation is reported:

Form elements must have labels

### What happens
When using the Deque WorldSpace plugin for Chrome to test a "Search Form or Search Results" menu item (with "Use Search Options" turned on), the following accessibility violation is reported:

> Form elements must have labels
> Issue description
> Ensures every form element has a label
> 
> Impact: critical
>  Learn more
> Element location
> input[autocomplete="off"]
> Element source
> <input type="text" autocomplete="off" readonly="">
> To solve this violation, you need to:
> Fix at least one (1) of these issues:
> aria-label attribute does not exist or is empty
> 
> aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
> 
> Form element does not have an implicit (wrapped) <label>
> 
> Form element does not have an explicit <label>
> 
> Element has no title attribute or the title attribute is empty

See screenshot: 

![search-form-missing-label](https://user-images.githubusercontent.com/35043141/58978305-90c3ae00-8799-11e9-805d-524c01fab897.png)

### What do you expect

No violations should be reported.

### Steps to reproduce

Create a "Search Form or Search Results" menu item 
On the "Options" tab of the menu item, set "Use Search Options" to "Yes"
Test the menu item with Deque WorldSpace plugin for Chrome

**Comment by Krshivam25** [comment]
Hi, @eddiekonczal I would like to contribute to this please help me to get started.

**Comment by eddiekonczal** [comment]
Hi, @Krshivam25 - it appears this issue was resolved in Joomla! 3.9.9.

See:
https://github.com/joomla/joomla-cms/pull/24623
https://github.com/joomla/joomla-cms/issues/25127

Thanks for following up!
-Eddie
