### ISSUE TITLE
Backend login issues

### ISSUE THREAD

**Issue by carcam** [joomla/accessibility#69]
## [Operable 2.1.1] Only form is reachable using keyboard

At backend login you can only reach the form using the keyboard (https://a11ytests.joomla.com/administrator). You cannot reach any of the support links or the go to frontpage link.

### How to fix (in case you know what needs to be changed)

Stablish correct landmarks for the page so that they can be easily accessed

**Comment by wilsonge** [comment]
I can reach all the links from the keyboard in chrome. how are you reproducing this?

**Comment by carcam** [comment]
Interesting!! I tested this in Firefox and I have retested and it keeps happening.

As you said, in Chrome, you can reach all the links and even you can get the "Skip to" links. But in any case, the skip to link should be the first thing you can reach on the page, isn't it?

**Comment by chmst** [comment]
I tested in FF and it starts on the login form, which is ok, I think. 
The skip-to-link indeed appears only sometimes if you tab troough the window, ~~but is has no target links which is an issue~~ my fault :)  I had replace the module by an image.

@carcam In the login screen the focus is set directly to the login form. I think that this is right because it is the only feature of a login screen, and we can assume the a user wants to start with entering the username at once.

**Comment by carcam** [comment]
My feeling is that the skip to links module offers a great page overview (same as browsing visually) so I thought having it first makes sense. If no other elements on the page avoiding it is ok, but as we have the links on the left it might be a good idea to reconsider...

**Comment by hans2103** [comment]
As @chmst mentions " In the login screen the focus is set directly to the login form."
When you press tab you go to the next field. Press again and again and again and.... you know the drill. After focus on "Forgot your login details?" the focus shifts to the first link in the sidebar. 
@carcam seems correct to me.

**Comment by brianteeman** [comment]
What is the problem? Everything seems correct to me.

![keyb](https://user-images.githubusercontent.com/1296369/87454890-83affa00-c5fc-11ea-9a24-fbab98374831.gif)

**Comment by carcam** [comment]
Hi @brianteeman,
actually it seems the problem happens on my testing box with Firefox so as you and others have pointed this issue is not valid. So just closing it right now ;)
