### ISSUE TITLE
Broken links on Github docs

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/accessibility#7]
## Broken links on Github docs
The XX is the area and x.x.x is the criteria code for example 2.4.1

### Description of the issue
When I trying to open links eg in the _sidebar file, the 404 error page opens.

### Steps to reproduce
Explain step by step how to reproduce the issue or how the feature must work.
1. Go to the accessibility/docs/
2. Open _sidebar.md
3. Click link eg to Checkboxes

**Comment by uglyeoin** [comment]
When I go here: https://github.com/joomla/accessibility/blob/master/docs/_sidebar.md and I look at quickstart for example, it is not a link to quickstart.md just quickstart.  Which is a 404 I think adding .md to the end will fix it.

**Comment by uglyeoin** [comment]
Ok what we need to do is remove the beginning /

**Comment by uglyeoin** [comment]
Resolved this can be closed now.

**Comment by armenos** [comment]
Thank you @uglyeoin it works
